# Generated by Django 4.0.2 on 2022-04-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
