# Generated by Django 4.0.2 on 2022-04-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_orderupdate_order_id_orderupdate_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
