# Generated by Django 4.0.2 on 2022-04-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_orderupdate_update_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(default='Order has been placed.. ', max_length=5000),
        ),
    ]
